<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<PackageId>Hengam</PackageId>
		<Version>0.1.0</Version>
		<Authors>Arya</Authors>
		<Description>Persian date, time, number, and localization utilities for .NET.</Description>
		<PackageTags>persian;jalali;date;time;localization;iranian;dotnet</PackageTags>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<RepositoryUrl>https://github.com/aryabaladi1/Hengam.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

</Project>